name: Deploy React Project

on: 
  push:
    braches: 'master'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v7 
      - name: setup node JS
        uses: actions/setup-node@v6
        with:
          node-version: '18'
      - name: veriyf node version
        run: node -v
      - name: verify npm version
        run: npm -v 
      - name: Install npm dependencies 
        run: npm ci
      - name: Run tests
        run: npm run test 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo code
        uses: actions/checkout@v7 
      - name: setup node JS
        uses: actions/setup-node@v6
        with:
          node-version: '18'
      - name: veriyf node version
        run: node -v
      - name: verify npm version
        run: npm -v 
      - name: Install npm dependencies 
        run: npm ci
      - name: Build react app
        run: npm run build
      - name: Deploy
        run: echo "Deploying...."




